# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kathleen McGrory
description: Kathleen McGrory is a reporter on the Tampa Bay Times investigations team. She was previously the newspaper’s health and medicine reporter.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kathleenmcgrory.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
